### ISSUE TITLE
ResultReuseByAgeConfiguration parameter

### ISSUE THREAD

**Issue by jamesp26** [yeremenkov/athena-query-client#1]
This is a lovely simple wrapper around athena.

Only 'issue' is the hardcoded setting for ResultReuseByAgeConfiguration. Any chance we can set this in the constructor? My preference is to always have this off.

**Comment by yeremenkov** [comment]
@jamesp26 Hey, I appreciate your interest in my simple package. 
I've added the option to change **ResultReuseConfiguration** and **WorkGroup**. 
The new version, 1.0.2, has been published to npm, so you can use it now. 
Please try it out and let me know what you think.
